name: Git push into leejiho9898/landing

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Creates output
        run: sh ./build.sh
      - name: output output
        run: echo 'output'

      # - name: Push to another repository
